---
- name: packages and tool installation
  hosts: all

  tasks:
  - name: update
    apt:
     name: update
     state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: upgrade
    apt:
     name: upgrade
     state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'    

  - name: change hostname to myserver
    hostname:
     name: "rke-sit-mgr"
    when: ansible_distribution == 'rke-sit-mgr'

  - name: change hostname to myserver
    hostname:
     name: "rke-sit-con-01"
    when: ansible_distribution == 'rke-sit-con-01'

  - name: change hostname to myserver
    hostname:
     name: "rke-sit-con-02"
    when: ansible_distribution == 'rke-sit-con-02'

  - name: change hostname to myserver
    hostname:
     name: "rke-sit-mgr"
    when: ansible_distribution == 'rke-sit-mgr'